//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Kv17Receiver.bison {
    
    using System.Xml.Serialization;
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/core", IsNullable=false)]
    public partial class delimiter {
        
        private string sinceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string since {
            get {
                return this.sinceField;
            }
            set {
                this.sinceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class MUTATIONMESSAGEType {
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private int reasontypeField;
        
        private string subreasontypeField;
        
        private string reasoncontentField;
        
        private int advicetypeField;
        
        private string subadvicetypeField;
        
        private string advicecontentField;
        
        private showcancelledtripType showcancelledtripField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        public MUTATIONMESSAGEType() {
            this.showcancelledtripField = showcancelledtripType.@true;
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public int reasontype {
            get {
                return this.reasontypeField;
            }
            set {
                this.reasontypeField = value;
            }
        }
        
        /// <remarks/>
        public string subreasontype {
            get {
                return this.subreasontypeField;
            }
            set {
                this.subreasontypeField = value;
            }
        }
        
        /// <remarks/>
        public string reasoncontent {
            get {
                return this.reasoncontentField;
            }
            set {
                this.reasoncontentField = value;
            }
        }
        
        /// <remarks/>
        public int advicetype {
            get {
                return this.advicetypeField;
            }
            set {
                this.advicetypeField = value;
            }
        }
        
        /// <remarks/>
        public string subadvicetype {
            get {
                return this.subadvicetypeField;
            }
            set {
                this.subadvicetypeField = value;
            }
        }
        
        /// <remarks/>
        public string advicecontent {
            get {
                return this.advicecontentField;
            }
            set {
                this.advicecontentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(showcancelledtripType.@true)]
        public showcancelledtripType showcancelledtrip {
            get {
                return this.showcancelledtripField;
            }
            set {
                this.showcancelledtripField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public enum showcancelledtripType {
        
        /// <remarks/>
        @false,
        
        /// <remarks/>
        @true,
        
        /// <remarks/>
        message,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class LAGType {
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private int lagtimeField;
        
        private AlertCauseEnumeration alertcauseField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        public LAGType() {
            this.alertcauseField = AlertCauseEnumeration.unknown;
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public int lagtime {
            get {
                return this.lagtimeField;
            }
            set {
                this.lagtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(AlertCauseEnumeration.unknown)]
        public AlertCauseEnumeration alertcause {
            get {
                return this.alertcauseField;
            }
            set {
                this.alertcauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public enum AlertCauseEnumeration {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        technicalProblem,
        
        /// <remarks/>
        breakDown,
        
        /// <remarks/>
        accident,
        
        /// <remarks/>
        collision,
        
        /// <remarks/>
        poorWeather,
        
        /// <remarks/>
        fallenTree,
        
        /// <remarks/>
        staffSickness,
        
        /// <remarks/>
        staffAbsence,
        
        /// <remarks/>
        previousDisturbances,
        
        /// <remarks/>
        securityAlert,
        
        /// <remarks/>
        emergencyServicesCall,
        
        /// <remarks/>
        policeActivity,
        
        /// <remarks/>
        policeOrder,
        
        /// <remarks/>
        fire,
        
        /// <remarks/>
        cableFire,
        
        /// <remarks/>
        smokeDetectedOnVehicle,
        
        /// <remarks/>
        fireAtStation,
        
        /// <remarks/>
        fireRun,
        
        /// <remarks/>
        fireBrigadeOrder,
        
        /// <remarks/>
        explosion,
        
        /// <remarks/>
        explosionHazard,
        
        /// <remarks/>
        bombDisposal,
        
        /// <remarks/>
        emergencyMedicalServices,
        
        /// <remarks/>
        emergencyBrake,
        
        /// <remarks/>
        vandalism,
        
        /// <remarks/>
        cableTheft,
        
        /// <remarks/>
        signalPassedAtDanger,
        
        /// <remarks/>
        stationOverrun,
        
        /// <remarks/>
        passengersBlockingDoors,
        
        /// <remarks/>
        defectiveSecuritySystem,
        
        /// <remarks/>
        overcrowded,
        
        /// <remarks/>
        borderControl,
        
        /// <remarks/>
        unattendedBag,
        
        /// <remarks/>
        telephonedThreat,
        
        /// <remarks/>
        suspectVehicle,
        
        /// <remarks/>
        evacuation,
        
        /// <remarks/>
        terroristIncident,
        
        /// <remarks/>
        publicDisturbance,
        
        /// <remarks/>
        vehicleFailure,
        
        /// <remarks/>
        serviceDisruption,
        
        /// <remarks/>
        doorFailure,
        
        /// <remarks/>
        lightingFailure,
        
        /// <remarks/>
        pointsProblem,
        
        /// <remarks/>
        pointsFailure,
        
        /// <remarks/>
        signalProblem,
        
        /// <remarks/>
        signalFailure,
        
        /// <remarks/>
        overheadWireFailure,
        
        /// <remarks/>
        levelCrossingFailure,
        
        /// <remarks/>
        trafficManagementSystemFailure,
        
        /// <remarks/>
        engineFailure,
        
        /// <remarks/>
        repairWork,
        
        /// <remarks/>
        constructionWork,
        
        /// <remarks/>
        maintenanceWork,
        
        /// <remarks/>
        powerProblem,
        
        /// <remarks/>
        trackCircuitProblem,
        
        /// <remarks/>
        swingBridgeFailure,
        
        /// <remarks/>
        escalatorFailure,
        
        /// <remarks/>
        liftFailure,
        
        /// <remarks/>
        gangwayProblem,
        
        /// <remarks/>
        defectiveVehicle,
        
        /// <remarks/>
        brokenRail,
        
        /// <remarks/>
        poorRailConditions,
        
        /// <remarks/>
        deicingWork,
        
        /// <remarks/>
        wheelProblem,
        
        /// <remarks/>
        routeBlockage,
        
        /// <remarks/>
        congestion,
        
        /// <remarks/>
        heavyTraffic,
        
        /// <remarks/>
        routeDiversion,
        
        /// <remarks/>
        roadworks,
        
        /// <remarks/>
        unscheduledConstructionWork,
        
        /// <remarks/>
        levelCrossingIncident,
        
        /// <remarks/>
        sewerageMaintenance,
        
        /// <remarks/>
        roadClosed,
        
        /// <remarks/>
        roadwayDamage,
        
        /// <remarks/>
        bridgeDamage,
        
        /// <remarks/>
        personOnTheLine,
        
        /// <remarks/>
        objectOnTheLine,
        
        /// <remarks/>
        vehicleOnTheLine,
        
        /// <remarks/>
        animalOnTheLine,
        
        /// <remarks/>
        fallenTreeOnTheLine,
        
        /// <remarks/>
        vegetation,
        
        /// <remarks/>
        speedRestrictions,
        
        /// <remarks/>
        precedingVehicle,
        
        /// <remarks/>
        nearMiss,
        
        /// <remarks/>
        personHitByVehicle,
        
        /// <remarks/>
        vehicleStruckObject,
        
        /// <remarks/>
        vehicleStruckAnimal,
        
        /// <remarks/>
        derailment,
        
        /// <remarks/>
        levelCrossingAccident,
        
        /// <remarks/>
        fog,
        
        /// <remarks/>
        heavySnowFall,
        
        /// <remarks/>
        heavyRain,
        
        /// <remarks/>
        strongWinds,
        
        /// <remarks/>
        ice,
        
        /// <remarks/>
        hail,
        
        /// <remarks/>
        highTemperatures,
        
        /// <remarks/>
        flooding,
        
        /// <remarks/>
        lowWaterLevel,
        
        /// <remarks/>
        riskOfFlooding,
        
        /// <remarks/>
        highWaterLevel,
        
        /// <remarks/>
        fallenLeaves,
        
        /// <remarks/>
        landslide,
        
        /// <remarks/>
        riskOfLandslide,
        
        /// <remarks/>
        driftingSnow,
        
        /// <remarks/>
        blizzardConditions,
        
        /// <remarks/>
        stormDamage,
        
        /// <remarks/>
        lightningStrike,
        
        /// <remarks/>
        roughSea,
        
        /// <remarks/>
        highTide,
        
        /// <remarks/>
        lowTide,
        
        /// <remarks/>
        iceDrift,
        
        /// <remarks/>
        avalanches,
        
        /// <remarks/>
        riskOfAvalanches,
        
        /// <remarks/>
        flashFloods,
        
        /// <remarks/>
        mudslide,
        
        /// <remarks/>
        rockfalls,
        
        /// <remarks/>
        subsidence,
        
        /// <remarks/>
        earthquakeDamage,
        
        /// <remarks/>
        grassFire,
        
        /// <remarks/>
        wildlandFire,
        
        /// <remarks/>
        iceOnRailway,
        
        /// <remarks/>
        iceOnCarriages,
        
        /// <remarks/>
        specialEvent,
        
        /// <remarks/>
        procession,
        
        /// <remarks/>
        demonstration,
        
        /// <remarks/>
        industrialAction,
        
        /// <remarks/>
        operatorCeasedTrading,
        
        /// <remarks/>
        vehicleBlockingTrack,
        
        /// <remarks/>
        foreignDisturbances,
        
        /// <remarks/>
        awaitingShuttle,
        
        /// <remarks/>
        changeInCarriages,
        
        /// <remarks/>
        trainCoupling,
        
        /// <remarks/>
        boardingDelay,
        
        /// <remarks/>
        awaitingApproach,
        
        /// <remarks/>
        overtaking,
        
        /// <remarks/>
        provisionDelay,
        
        /// <remarks/>
        miscellaneous,
        
        /// <remarks/>
        undefinedAlertCause,
        
        /// <remarks/>
        incident,
        
        /// <remarks/>
        safetyViolation,
        
        /// <remarks/>
        trainDoor,
        
        /// <remarks/>
        altercation,
        
        /// <remarks/>
        illVehicleOccupants,
        
        /// <remarks/>
        serviceFailure,
        
        /// <remarks/>
        bombExplosion,
        
        /// <remarks/>
        fireBrigadeSafetyChecks,
        
        /// <remarks/>
        civilEmergency,
        
        /// <remarks/>
        airRaid,
        
        /// <remarks/>
        sabotage,
        
        /// <remarks/>
        bombAlert,
        
        /// <remarks/>
        attack,
        
        /// <remarks/>
        gunfireOnRoadway,
        
        /// <remarks/>
        securityIncident,
        
        /// <remarks/>
        linesideFire,
        
        /// <remarks/>
        passengerAction,
        
        /// <remarks/>
        staffAssault,
        
        /// <remarks/>
        railwayCrime,
        
        /// <remarks/>
        assault,
        
        /// <remarks/>
        theft,
        
        /// <remarks/>
        fatality,
        
        /// <remarks/>
        personUnderTrain,
        
        /// <remarks/>
        personHitByTrain,
        
        /// <remarks/>
        personIllOnVehicle,
        
        /// <remarks/>
        emergencyServices,
        
        /// <remarks/>
        insufficientDemand,
        
        /// <remarks/>
        leaderBoardFailure,
        
        /// <remarks/>
        serviceIndicatorFailure,
        
        /// <remarks/>
        operatorSuspended,
        
        /// <remarks/>
        problemsAtBorderPost,
        
        /// <remarks/>
        problemsAtCustomsPost,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("levelCrossingIncident")]
        levelCrossingIncident1,
        
        /// <remarks/>
        trainStruckAnimal,
        
        /// <remarks/>
        trainStruckObject,
        
        /// <remarks/>
        roadMaintenance,
        
        /// <remarks/>
        asphalting,
        
        /// <remarks/>
        paving,
        
        /// <remarks/>
        march,
        
        /// <remarks/>
        filterBlockade,
        
        /// <remarks/>
        sightseersObstructingAccess,
        
        /// <remarks/>
        holiday,
        
        /// <remarks/>
        bridgeStrike,
        
        /// <remarks/>
        viaductFailure,
        
        /// <remarks/>
        overheadObstruction,
        
        /// <remarks/>
        undefinedProblem,
        
        /// <remarks/>
        logisticProblems,
        
        /// <remarks/>
        problemsOnLocalRoad,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("undefinedProblem")]
        undefinedProblem1,
        
        /// <remarks/>
        staffInjury,
        
        /// <remarks/>
        contractorStaffInjury,
        
        /// <remarks/>
        staffInWrongPlace,
        
        /// <remarks/>
        staffShortage,
        
        /// <remarks/>
        unofficialIndustrialAction,
        
        /// <remarks/>
        workToRule,
        
        /// <remarks/>
        undefinedPersonnelProblem,
        
        /// <remarks/>
        trainWarningSystemProblem,
        
        /// <remarks/>
        signalAndSwitchFailure,
        
        /// <remarks/>
        tractionFailure,
        
        /// <remarks/>
        defectiveTrain,
        
        /// <remarks/>
        wheelImpactLoad,
        
        /// <remarks/>
        lackOfOperationalStock,
        
        /// <remarks/>
        defectiveFireAlarmEquipment,
        
        /// <remarks/>
        defectivePlatformEdgeDoors,
        
        /// <remarks/>
        defectiveCctv,
        
        /// <remarks/>
        defectivePublicAnnouncementSystem,
        
        /// <remarks/>
        ticketingSystemNotAvailable,
        
        /// <remarks/>
        emergencyEngineeringWork,
        
        /// <remarks/>
        lateFinishToEngineeringWork,
        
        /// <remarks/>
        fuelProblem,
        
        /// <remarks/>
        closedForMaintenance,
        
        /// <remarks/>
        fuelShortage,
        
        /// <remarks/>
        slipperyTrack,
        
        /// <remarks/>
        luggageCarouselProblem,
        
        /// <remarks/>
        undefinedEquipmentProblem,
        
        /// <remarks/>
        stormConditions,
        
        /// <remarks/>
        tidalRestrictions,
        
        /// <remarks/>
        slipperiness,
        
        /// <remarks/>
        glazedFrost,
        
        /// <remarks/>
        frozen,
        
        /// <remarks/>
        sleet,
        
        /// <remarks/>
        waterlogged,
        
        /// <remarks/>
        sewerOverflow,
        
        /// <remarks/>
        undefinedEnvironmentalProblem,
        
        /// <remarks/>
        fireAtTheStation,
        
        /// <remarks/>
        breakdown,
        
        /// <remarks/>
        levelCrossingBlocked,
        
        /// <remarks/>
        heavySnowfall,
        
        /// <remarks/>
        waitingForTransferPassengers,
        
        /// <remarks/>
        awaitingOncomingVehicle,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class CHANGEDESTINATIONType {
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private string destinationcodeField;
        
        private string destinationname50Field;
        
        private string destinationname16Field;
        
        private string destinationdetail16Field;
        
        private string destinationdisplay16Field;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public string destinationcode {
            get {
                return this.destinationcodeField;
            }
            set {
                this.destinationcodeField = value;
            }
        }
        
        /// <remarks/>
        public string destinationname50 {
            get {
                return this.destinationname50Field;
            }
            set {
                this.destinationname50Field = value;
            }
        }
        
        /// <remarks/>
        public string destinationname16 {
            get {
                return this.destinationname16Field;
            }
            set {
                this.destinationname16Field = value;
            }
        }
        
        /// <remarks/>
        public string destinationdetail16 {
            get {
                return this.destinationdetail16Field;
            }
            set {
                this.destinationdetail16Field = value;
            }
        }
        
        /// <remarks/>
        public string destinationdisplay16 {
            get {
                return this.destinationdisplay16Field;
            }
            set {
                this.destinationdisplay16Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class CHANGEPASSTIMESType {
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private string targetarrivaltimeField;
        
        private string targetdeparturetimeField;
        
        private journeystoptypeType journeystoptypeField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        public string targetarrivaltime {
            get {
                return this.targetarrivaltimeField;
            }
            set {
                this.targetarrivaltimeField = value;
            }
        }
        
        /// <remarks/>
        public string targetdeparturetime {
            get {
                return this.targetdeparturetimeField;
            }
            set {
                this.targetdeparturetimeField = value;
            }
        }
        
        /// <remarks/>
        public journeystoptypeType journeystoptype {
            get {
                return this.journeystoptypeField;
            }
            set {
                this.journeystoptypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public enum journeystoptypeType {
        
        /// <remarks/>
        FIRST,
        
        /// <remarks/>
        INTERMEDIATE,
        
        /// <remarks/>
        LAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class SHORTENType {
        
        private string userstopcodeField;
        
        private int passagesequencenumberField;
        
        private showcancelledtripType showcancelledtripField;
        
        private AlertCauseEnumeration alertcauseField;
        
        private ServiceConditionEnumeration serviceconditionField;
        
        private string servicerefField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        public SHORTENType() {
            this.showcancelledtripField = showcancelledtripType.@true;
            this.alertcauseField = AlertCauseEnumeration.unknown;
            this.serviceconditionField = ServiceConditionEnumeration.unknown;
            this.servicerefField = "false";
        }
        
        /// <remarks/>
        public string userstopcode {
            get {
                return this.userstopcodeField;
            }
            set {
                this.userstopcodeField = value;
            }
        }
        
        /// <remarks/>
        public int passagesequencenumber {
            get {
                return this.passagesequencenumberField;
            }
            set {
                this.passagesequencenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(showcancelledtripType.@true)]
        public showcancelledtripType showcancelledtrip {
            get {
                return this.showcancelledtripField;
            }
            set {
                this.showcancelledtripField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(AlertCauseEnumeration.unknown)]
        public AlertCauseEnumeration alertcause {
            get {
                return this.alertcauseField;
            }
            set {
                this.alertcauseField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ServiceConditionEnumeration.unknown)]
        public ServiceConditionEnumeration servicecondition {
            get {
                return this.serviceconditionField;
            }
            set {
                this.serviceconditionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string serviceref {
            get {
                return this.servicerefField;
            }
            set {
                this.servicerefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public enum ServiceConditionEnumeration {
        
        /// <remarks/>
        unknown,
        
        /// <remarks/>
        delay,
        
        /// <remarks/>
        minorDelays,
        
        /// <remarks/>
        majorDelays,
        
        /// <remarks/>
        operationTimeExtension,
        
        /// <remarks/>
        onTime,
        
        /// <remarks/>
        disturbanceRectified,
        
        /// <remarks/>
        changeOfPlatform,
        
        /// <remarks/>
        lineCancellation,
        
        /// <remarks/>
        tripCancellation,
        
        /// <remarks/>
        boarding,
        
        /// <remarks/>
        goToGate,
        
        /// <remarks/>
        stopCancelled,
        
        /// <remarks/>
        stopMoved,
        
        /// <remarks/>
        stopOnDemand,
        
        /// <remarks/>
        additionalStop,
        
        /// <remarks/>
        substitutedStop,
        
        /// <remarks/>
        diverted,
        
        /// <remarks/>
        disruption,
        
        /// <remarks/>
        limitedOperation,
        
        /// <remarks/>
        discontinuedOperation,
        
        /// <remarks/>
        irregularTraffic,
        
        /// <remarks/>
        wagonOrderChanged,
        
        /// <remarks/>
        trainShortened,
        
        /// <remarks/>
        additionalRide,
        
        /// <remarks/>
        replacementRide,
        
        /// <remarks/>
        temporarilyNonStopping,
        
        /// <remarks/>
        temporaryStopplace,
        
        /// <remarks/>
        undefinedStatus,
        
        /// <remarks/>
        altered,
        
        /// <remarks/>
        cancelled,
        
        /// <remarks/>
        delayed,
        
        /// <remarks/>
        noService,
        
        /// <remarks/>
        disrupted,
        
        /// <remarks/>
        additionalService,
        
        /// <remarks/>
        specialService,
        
        /// <remarks/>
        normalService,
        
        /// <remarks/>
        intermittentService,
        
        /// <remarks/>
        shortFormedService,
        
        /// <remarks/>
        fullLengthService,
        
        /// <remarks/>
        extendedService,
        
        /// <remarks/>
        splittingTrain,
        
        /// <remarks/>
        replacementTransport,
        
        /// <remarks/>
        arrivesEarly,
        
        /// <remarks/>
        shuttleService,
        
        /// <remarks/>
        replacementService,
        
        /// <remarks/>
        undefinedServiceInformation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class KV17mutatejourneystopType {
        
        private System.DateTime timestampField;
        
        private SHORTENType[] sHORTENField;
        
        private CHANGEPASSTIMESType[] cHANGEPASSTIMESField;
        
        private CHANGEDESTINATIONType[] cHANGEDESTINATIONField;
        
        private LAGType[] lAGField;
        
        private MUTATIONMESSAGEType[] mUTATIONMESSAGEField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SHORTEN")]
        public SHORTENType[] SHORTEN {
            get {
                return this.sHORTENField;
            }
            set {
                this.sHORTENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CHANGEPASSTIMES")]
        public CHANGEPASSTIMESType[] CHANGEPASSTIMES {
            get {
                return this.cHANGEPASSTIMESField;
            }
            set {
                this.cHANGEPASSTIMESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CHANGEDESTINATION")]
        public CHANGEDESTINATIONType[] CHANGEDESTINATION {
            get {
                return this.cHANGEDESTINATIONField;
            }
            set {
                this.cHANGEDESTINATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAG")]
        public LAGType[] LAG {
            get {
                return this.lAGField;
            }
            set {
                this.lAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MUTATIONMESSAGE")]
        public MUTATIONMESSAGEType[] MUTATIONMESSAGE {
            get {
                return this.mUTATIONMESSAGEField;
            }
            set {
                this.mUTATIONMESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class NOTMONITOREDType {
        
        private monitoringerrorType monitoringerrorField;
        
        private bool monitoringerrorFieldSpecified;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public monitoringerrorType monitoringerror {
            get {
                return this.monitoringerrorField;
            }
            set {
                this.monitoringerrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monitoringerrorSpecified {
            get {
                return this.monitoringerrorFieldSpecified;
            }
            set {
                this.monitoringerrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public enum monitoringerrorType {
        
        /// <remarks/>
        GPS,
        
        /// <remarks/>
        GPRS,
        
        /// <remarks/>
        Radio,
        
        /// <remarks/>
        General,
        
        /// <remarks/>
        NoSystem,
        
        /// <remarks/>
        other,
        
        /// <remarks/>
        unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class ADDType {
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class RECOVERType {
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class CANCELType {
        
        private int reasontypeField;
        
        private string subreasontypeField;
        
        private string reasoncontentField;
        
        private int advicetypeField;
        
        private string subadvicetypeField;
        
        private string advicecontentField;
        
        private showcancelledtripType showcancelledtripField;
        
        private bool autorecoverField;
        
        private AlertCauseEnumeration alertcauseField;
        
        private ServiceConditionEnumeration serviceconditionField;
        
        private string servicerefField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        public CANCELType() {
            this.showcancelledtripField = showcancelledtripType.@true;
            this.autorecoverField = false;
            this.alertcauseField = AlertCauseEnumeration.unknown;
            this.serviceconditionField = ServiceConditionEnumeration.unknown;
            this.servicerefField = "false";
        }
        
        /// <remarks/>
        public int reasontype {
            get {
                return this.reasontypeField;
            }
            set {
                this.reasontypeField = value;
            }
        }
        
        /// <remarks/>
        public string subreasontype {
            get {
                return this.subreasontypeField;
            }
            set {
                this.subreasontypeField = value;
            }
        }
        
        /// <remarks/>
        public string reasoncontent {
            get {
                return this.reasoncontentField;
            }
            set {
                this.reasoncontentField = value;
            }
        }
        
        /// <remarks/>
        public int advicetype {
            get {
                return this.advicetypeField;
            }
            set {
                this.advicetypeField = value;
            }
        }
        
        /// <remarks/>
        public string subadvicetype {
            get {
                return this.subadvicetypeField;
            }
            set {
                this.subadvicetypeField = value;
            }
        }
        
        /// <remarks/>
        public string advicecontent {
            get {
                return this.advicecontentField;
            }
            set {
                this.advicecontentField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(showcancelledtripType.@true)]
        public showcancelledtripType showcancelledtrip {
            get {
                return this.showcancelledtripField;
            }
            set {
                this.showcancelledtripField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool autorecover {
            get {
                return this.autorecoverField;
            }
            set {
                this.autorecoverField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(AlertCauseEnumeration.unknown)]
        public AlertCauseEnumeration alertcause {
            get {
                return this.alertcauseField;
            }
            set {
                this.alertcauseField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(ServiceConditionEnumeration.unknown)]
        public ServiceConditionEnumeration servicecondition {
            get {
                return this.serviceconditionField;
            }
            set {
                this.serviceconditionField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string serviceref {
            get {
                return this.servicerefField;
            }
            set {
                this.servicerefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class KV17mutatejourneyType {
        
        private System.DateTime timestampField;
        
        private object itemField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ADD", typeof(ADDType))]
        [System.Xml.Serialization.XmlElementAttribute("CANCEL", typeof(CANCELType))]
        [System.Xml.Serialization.XmlElementAttribute("NOTMONITORED", typeof(NOTMONITOREDType))]
        [System.Xml.Serialization.XmlElementAttribute("RECOVER", typeof(RECOVERType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class KV17journeyType {
        
        private string dataownercodeField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string begintimeField;
        
        private string endtimeField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string dataownercode {
            get {
                return this.dataownercodeField;
            }
            set {
                this.dataownercodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("allJourneysOfLine", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("allLines", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("journeynumber", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("lineplanningnumber", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("operatingday", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("reinforcementnumber", typeof(int))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string begintime {
            get {
                return this.begintimeField;
            }
            set {
                this.begintimeField = value;
            }
        }
        
        /// <remarks/>
        public string endtime {
            get {
                return this.endtimeField;
            }
            set {
                this.endtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        allJourneysOfLine,
        
        /// <remarks/>
        allLines,
        
        /// <remarks/>
        journeynumber,
        
        /// <remarks/>
        lineplanningnumber,
        
        /// <remarks/>
        operatingday,
        
        /// <remarks/>
        reinforcementnumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public partial class KV17cvlinfoType {
        
        private KV17journeyType kV17JOURNEYField;
        
        private KV17mutatejourneyType kV17MUTATEJOURNEYField;
        
        private KV17mutatejourneystopType kV17MUTATEJOURNEYSTOPField;
        
        private delimiter[] delimiterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public KV17journeyType KV17JOURNEY {
            get {
                return this.kV17JOURNEYField;
            }
            set {
                this.kV17JOURNEYField = value;
            }
        }
        
        /// <remarks/>
        public KV17mutatejourneyType KV17MUTATEJOURNEY {
            get {
                return this.kV17MUTATEJOURNEYField;
            }
            set {
                this.kV17MUTATEJOURNEYField = value;
            }
        }
        
        /// <remarks/>
        public KV17mutatejourneystopType KV17MUTATEJOURNEYSTOP {
            get {
                return this.kV17MUTATEJOURNEYSTOPField;
            }
            set {
                this.kV17MUTATEJOURNEYSTOPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delimiter", Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
        public delimiter[] delimiter {
            get {
                return this.delimiterField;
            }
            set {
                this.delimiterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv17/core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/core", IsNullable=false)]
    public partial class end {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg", IsNullable=false)]
    public partial class VV_TM_PUSH {
        
        private string subscriberIDField;
        
        private string versionField;
        
        private DossierNameType dossierNameField;
        
        private System.DateTime timestampField;
        
        private KV17cvlinfoType[] kV17cvlinfoField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DossierNameType DossierName {
            get {
                return this.dossierNameField;
            }
            set {
                this.dossierNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KV17cvlinfo")]
        public KV17cvlinfoType[] KV17cvlinfo {
            get {
                return this.kV17cvlinfoField;
            }
            set {
                this.kV17cvlinfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public enum DossierNameType {
        
        /// <remarks/>
        KV17cvlinfo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg", IsNullable=false)]
    public partial class VV_TM_REQ {
        
        private string subscriberIDField;
        
        private string versionField;
        
        private DossierNameType dossierNameField;
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DossierNameType DossierName {
            get {
                return this.dossierNameField;
            }
            set {
                this.dossierNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg", IsNullable=false)]
    public partial class VV_TM_RES {
        
        private string subscriberIDField;
        
        private string versionField;
        
        private DossierNameType dossierNameField;
        
        private System.DateTime timestampField;
        
        private ResponseCodeType responseCodeField;
        
        private string responseErrorField;
        
        /// <remarks/>
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public DossierNameType DossierName {
            get {
                return this.dossierNameField;
            }
            set {
                this.dossierNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        public ResponseCodeType ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseError {
            get {
                return this.responseErrorField;
            }
            set {
                this.responseErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "8.4.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bison.connekt.nl/tmi8/kv17/msg")]
    public enum ResponseCodeType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        NA,
        
        /// <remarks/>
        PE,
    }
}
